app_enquete/urls.py
from django.urls import path
from . import views

app_name = "app_enquete"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/results/", views.results, name='results'),
    path("<str:question_id>/vote/", views.vote, name='vote'),
]

enquete/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app_enquete/', include('app_enquete.urls')),
]

app_enquete/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

app_enquete/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect  
from django.urls import reverse
from .models import Question

# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "app_enquete/index.html", context)   

def results(request, question_id):
    question = Question(pk = question_id)
    return render(request, "app_enquete/results.html", {"question":question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    try:
        selected_choice = question.choice_set.get( pk = request.POST["choice"])
    except KeyError:
        return render(request, "app_enquete/vote.html",{
            "question":question,
            "error_message": "Você não selecionou uma alternativa.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("app_enquete:results", args = (question_id)))

app_enquete/templates/app_enquete/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title> Enquete </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {%if latest_question_list%}
            <ul>
                {%for question in latest_question_list%}
                    <li><a href="{% url 'app_enquete:vote' question.id%}">{{ question.question_text }} </a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p> No polls are a variable </p>
        {% endif %}                       
        <script src="" async defer></script>
    </body>
</html>

app_enquete/templates/app_enquete/results.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title> Resultado da Enquete </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
            <h1> {{ question.question_text }} </h1>
            <ul>
                {% for choice in question.choice_set.all %}
                    <li> {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>
                {% endfor %}
            </ul>
            <a href="{% url "app_enquete:vote" question.id %}">Votar de novo?</a>    
        <script src="" async defer></script>
    </body>
</html>

app_enquete/templates/app_enquete/vote.html
<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title> Vote na Enquete </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <form action="{% url "app_enquete:vote" question.id %}" method= "post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message}}</strong></p> {%endif%}
            {%  for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter}}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
        </form>
       <script src="" async defer></script>
    </body>
</html>